💡 🥊 Add Lightbox
hack4impact-uiuc/falling-fruit pull request #222
Opened 2021-11-16 02:37 UTC by code-arman

## Status:
:construction: In development

## Description
Allow users to view review images and full screen (see figma for design)

Fixes #120 

## Todos

## Screenshots

2021-11-19 10:14 UTC, SirajChokshi requested changes
Great work implementing this so far -- its definitely almost there.

A few things I noticed:
* Missing border-radii on image and modal
* Margin is too large on modal
<img width="267" alt="Screen Shot 2021-11-19 at 4 06 40 AM" src="https://user-images.githubusercontent.com/19193347/142605092-12508181-1e17-4f96-85b0-957987eb256b.png">

- In the above screenshot, the border looks off (reference the designs)
- The thumbnails beneath the review should be clickable

Left a few comments about code-style.

2021-11-19 10:14 UTC, SirajChokshi commented on src/utils/api.ts
> -export const getReviews = (
Great data mock for demo-ing, but lets remove any changes made to this file for prod

2021-11-19 10:14 UTC, SirajChokshi commented on src/components/entry/Lightbox.js
> +const ReviewContainer = styled.div`
We're missing a border-radius on this element.

2021-11-19 10:14 UTC, SirajChokshi commented on src/components/entry/Lightbox.js
> +    reviewSubImgIndex + 1 < reviewImages[currReviewIndex].length
this function is a little too pithy, maybe we could use some if/else so its a little more clear what's going on

2021-11-19 10:14 UTC, SirajChokshi commented on src/components/entry/Lightbox.js
> +const StyledReviewImage = styled.img`
We're missing a border radius on the image preview

2021-11-19 10:14 UTC, SirajChokshi commented on src/components/entry/Lightbox.js
> +  max-width: fit-content;
The implication of this max-width is that the children determine the size of the parent. This seems to work, but lets think more about what that suggests about how the Dialog should work (should it fit content or fit the page as a whole?)

2021-11-19 10:14 UTC, SirajChokshi commented on src/components/entry/Lightbox.js
> +              <SelectedImagePreview $small key={photo.thumb}>
Maybe we could use a wrapped version of `SelectedImagePreview` for both selected and unselected instances and have a prop that dictates if an instance is currently selected.

2021-12-05 00:40 UTC, Qrtn approved these changes

2021-12-14 03:58 UTC, daniel-moon32 approved these changes
Looks good!

2021-12-23 01:42 UTC, merged