Data table features
hack4impact-uiuc/falling-fruit pull request #226
Opened 2021-12-03 02:35 UTC by riyajain59

## Status:

:construction: In development
## Description

Fixes #<number>

## Todos

## Screenshots

2021-12-14 03:29 UTC, daniel-moon32 requested changes
Looks good. Minor things to change

2021-12-14 03:29 UTC, daniel-moon32 commented on package.json
> +    "@material-ui/core": "^4.12.3",
Remove material-ui from dependencies

2021-12-14 03:29 UTC, daniel-moon32 commented on src/components/table/DataTableProperties.js
>    color: ${({ theme }) => theme.secondaryText} !important;
I don't know if this was because you needed to override something, but I think typically !important is bad practice.

2021-12-14 03:29 UTC, daniel-moon32 commented on src/components/table/ImportsTable.jsx
> +// /about/dataset/:datasetID
What is this comment for?

2021-12-23 05:00 UTC, Qrtn approved these changes

2021-12-23 05:16 UTC, SirajChokshi approved these changes

2021-12-23 05:17 UTC, merged