Map labels
hack4impact-uiuc/falling-fruit pull request #88
Opened 2021-04-15 01:11 UTC by vasuchal

## Status: :construction: In development

## Description
Displays Map Labels under each location based on the boolean showLabels prop. The labels show the common name for the trees. 

Fixes #<number>

## Todos

## Screenshots

2021-04-16 16:56 UTC, Archna-1 approved these changes
LGTM! :)

2021-04-16 17:01 UTC, code-arman requested changes
Great work. The code looks good, but I feel like the experience/design itself needs more thought before the feature is merged in

It looks really good when the user is zoomed in really close, but other than that, it feels kinda weird. I wonder if Siraj would have ideas on a way to make it look less bad at mid level zoom.

-- Oops, just realize you mentioned this on slack as well, but i will still keep this comment i guesss

<img width="939" alt="Screen Shot 2021-04-16 at 11 51 43 AM" src="https://user-images.githubusercontent.com/46976119/115058220-a2ecf800-9eaa-11eb-9216-c684b28bad7d.png">
<img width="934" alt="Screen Shot 2021-04-16 at 11 47 59 AM" src="https://user-images.githubusercontent.com/46976119/115058225-a41e2500-9eaa-11eb-943a-6811a8bacde1.png">
<img width="939" alt="Screen Shot 2021-04-16 at 11 47 41 AM" src="https://user-images.githubusercontent.com/46976119/115058226-a41e2500-9eaa-11eb-8a21-c845a8cac8a2.png">

2021-04-18 00:33 UTC, Qrtn commented on src/components/map/Location.js
> +)
Does onClick still work? Does it get passed through the props?

2021-04-18 00:44 UTC, code-arman commented on src/components/map/Location.js
> +const StyledDiv = styled.div`
Name this better plz

2021-04-19 14:32 UTC, Qrtn approved these changes
Nice work Vasu! Great job figuring out the tricky CSS.

2021-04-19 20:46 UTC, merged